// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjiatigypaevbjsjynqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqaWF0aWd5cGFldmJqc2p5bnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTkwMDgsImV4cCI6MjA3MTM3NTAwOH0.dAI2JYYHweXn95XauecCC2MHTJZY6nBPrbjA3zoDe7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});